# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 677)
        MainWindow.setMinimumSize(QtCore.QSize(674, 609))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Similarity_View = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(
            self.Similarity_View.sizePolicy().hasHeightForWidth())
        self.Similarity_View.setSizePolicy(sizePolicy)
        self.Similarity_View.setMinimumSize(QtCore.QSize(651, 475))
        self.Similarity_View.setMaximumSize(QtCore.QSize(0, 475))
        self.Similarity_View.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Similarity_View.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Similarity_View.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff)
        self.Similarity_View.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff)
        self.Similarity_View.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Similarity_View.setShowGrid(True)
        self.Similarity_View.setGridStyle(QtCore.Qt.DashLine)
        self.Similarity_View.setWordWrap(True)
        self.Similarity_View.setCornerButtonEnabled(True)
        self.Similarity_View.setObjectName("Similarity_View")
        self.Similarity_View.setColumnCount(2)
        self.Similarity_View.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Similarity_View.setHorizontalHeaderItem(1, item)
        self.Similarity_View.horizontalHeader().setVisible(True)
        self.Similarity_View.horizontalHeader().setCascadingSectionResizes(
            False)
        self.Similarity_View.horizontalHeader().setDefaultSectionSize(300)
        self.Similarity_View.horizontalHeader().setMinimumSectionSize(35)
        self.Similarity_View.horizontalHeader().setSortIndicatorShown(False)
        self.Similarity_View.horizontalHeader().setStretchLastSection(True)
        self.Similarity_View.verticalHeader().setDefaultSectionSize(45)
        self.Similarity_View.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(
            self.Similarity_View, 5, 0, 1, 1,
            QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.UpBtn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.UpBtn_1.setMinimumSize(QtCore.QSize(251, 45))
        self.UpBtn_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.UpBtn_1.setCheckable(True)
        self.UpBtn_1.setObjectName("UpBtn_1")
        self.horizontalLayout.addWidget(self.UpBtn_1)
        self.UpBtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.UpBtn_2.setMinimumSize(QtCore.QSize(251, 45))
        self.UpBtn_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.UpBtn_2.setCheckable(True)
        self.UpBtn_2.setChecked(False)
        self.UpBtn_2.setObjectName("UpBtn_2")
        self.horizontalLayout.addWidget(self.UpBtn_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.MixerSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.MixerSlider.sizePolicy().hasHeightForWidth())
        self.MixerSlider.setSizePolicy(sizePolicy)
        self.MixerSlider.setMinimumSize(QtCore.QSize(651, 11))
        self.MixerSlider.setMaximumSize(QtCore.QSize(0, 0))
        self.MixerSlider.setAutoFillBackground(False)
        self.MixerSlider.setMaximum(100)
        self.MixerSlider.setSliderPosition(50)
        self.MixerSlider.setTracking(True)
        self.MixerSlider.setOrientation(QtCore.Qt.Horizontal)
        self.MixerSlider.setObjectName("MixerSlider")
        self.verticalLayout_2.addWidget(self.MixerSlider)
        self.SearchBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding,
            QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SearchBtn.sizePolicy().hasHeightForWidth())
        self.SearchBtn.setSizePolicy(sizePolicy)
        self.SearchBtn.setMinimumSize(QtCore.QSize(111, 51))
        self.SearchBtn.setMaximumSize(QtCore.QSize(3565, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.SearchBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Search_BUTTON.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchBtn.setIcon(icon)
        self.SearchBtn.setAutoDefault(False)
        self.SearchBtn.setDefault(False)
        self.SearchBtn.setFlat(False)
        self.SearchBtn.setObjectName("SearchBtn")
        self.verticalLayout_2.addWidget(
            self.SearchBtn, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Similarity_View.setSortingEnabled(False)
        item = self.Similarity_View.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.Similarity_View.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.Similarity_View.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.Similarity_View.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.Similarity_View.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.Similarity_View.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.Similarity_View.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.Similarity_View.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.Similarity_View.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.Similarity_View.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.Similarity_View.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Track Name"))
        item = self.Similarity_View.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Similarity"))
        self.UpBtn_1.setText(_translate("MainWindow", "Upload Track 1"))
        self.UpBtn_2.setText(_translate("MainWindow", "Upload Track 2"))
        self.SearchBtn.setText(_translate("MainWindow", "Find Track"))